version: 2.1
jobs:
  build_frontend:
    docker:
      - image: circleci/node:8.10-stretch-browsers
    working_directory: ~/komiser
    steps:
      - checkout
      - restore_cache:
          key: node-modules-{{checksum "dashboard/package.json"}}
      - run:
          name: Install dependencies
          command: cd dashboard && npm install
      - save_cache:
          key: node-modules-{{checksum "dashboard/package.json"}}
          paths:
            - dashboard/node_modules
      - run:
          name: Build artifact
          command: cd dashboard && npm run build
      - persist_to_workspace:
          root: dashboard
          paths:
            - dist
  build_cli:
    docker:
      - image: golang:1.10.3
    working_directory: /go/src/github.com/mlabouardy/komiser
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/dashboard
      - run:
          name: Install dependencies
          command: |
            go get -u github.com/tools/godep
            godep restore
      - run:
          name: Install go-bin-data
          command: |
           go get github.com/jteeuwen/go-bindata/...
           go get github.com/elazarl/go-bindata-assetfs/...
      - run:
         name: Fix path
         command: mv /tmp/dashboard/dist .
      - run:
         name: Create assets
         command: go-bindata-assetfs -o template.go dist/
      - run:
         name: Install gox
         command: go get github.com/mitchellh/gox
      - run:
         name: Build binary
         command: gox -osarch="linux/amd64 windows/amd64 darwin/amd64"
      - run:
         name: Install AWS CLI
         command: |
          apt-get update
          apt-get install -y awscli
          chmod +x komiser_windows_amd64.exe komiser_darwin_amd64 komiser_linux_amd64
      - run:
          name: Push Linux binary
          command: aws s3 cp komiser_linux_amd64 s3://komiser/2.4.0/linux/komiser --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers
      - run:
          name: Push Windows binary
          command: aws s3 cp komiser_windows_amd64.exe s3://komiser/2.4.0/windows/komiser --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers
      - run:
          name: Push Mac OS X binary
          command: aws s3 cp komiser_darwin_amd64 s3://komiser/2.4.0/osx/komiser --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers
      - run:
          name: Upload IAM policy
          command: aws s3 cp policy.json s3://komiser/policy.json --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers

  build_docker:
    docker:
       - image: docker:18.09.5
    steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Build Komiser Docker Image
            command: docker build -t mlabouardy/komiser:latest .
        - deploy:
            name: Push Komiser to DockerHub
            command: |
              docker login -u$DOCKERHUB_LOGIN -p$DOCKERHUB_PASSWORD
              docker tag mlabouardy/komiser:latest mlabouardy/komiser:${CIRCLE_SHA1}
              docker push mlabouardy/komiser:latest
              docker push mlabouardy/komiser:${CIRCLE_SHA1}
      
workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build_frontend
            - build_cli:
                requires:
                    - build_frontend
            - build_docker:
                requires:
                    - build_cli